### ISSUE TITLE
Extract generated prompt

### ISSUE THREAD

**Issue by klement** [alpertunga-bile/prompt-generator-comfyui#6]
I'm using SD Prompt Saver and would like to include generated positive prompt. How can I do that? SD Prompt Saver expects a string, while output of PromptGenerator is already CLIP encoded - if I understand it correctly.

It'd be great if PromptGenerator had an output containing the actual string before encoding. It doesn't really matter if it's a replacement for existing output (which one would then need to chain into CLIP Text Encode node) or a parallel output.

Thanks!

**Comment by alpertunga-bile** [comment]
Hello, thank you for suggesting a feature. I added the generated prompt to output as string with [new commit](https://github.com/alpertunga-bile/prompt-generator-comfyui/commit/d9802ea0d4344d0e82c56b51dc367be1a548d386). I'd appreciate your feedback on whether the update fixed your issue.

**Comment by klement** [comment]
Perfect! Thanks!
