### ISSUE TITLE
[BUG] UTF-8 not handled correctly

### ISSUE THREAD

**Issue by klement** [alpertunga-bile/prompt-generator-comfyui#7]
Hi!

an issue I noticed. If the input text for prompt-generator contains accented characters, for example:

ă

then prompt generator errors with an exception:

Error occurred when executing Prompt Generator:  'charmap' codec can't encode character '\u0159' in position 161: character maps to <undefined>

Thanks!

**Comment by alpertunga-bile** [comment]
Hello, thanks for reporting. With [new commit](https://github.com/alpertunga-bile/prompt-generator-comfyui/commit/46fb99369038e19500dd74de4e7e5d0ca3dd9ba9) I added encodings for ascii and utf-8. Checked the update with the character that you provided and it seems working now. If you encounter any problems let me know.

**Comment by klement** [comment]
Issue seems to be gone. Thank you!
