### ISSUE TITLE
[BUG]Import failed No module named 'keras.engine'

### ISSUE THREAD

**Issue by ultimatech-cn** [alpertunga-bile/prompt-generator-comfyui#8]
**Describe the bug**
Windows portable version. When starting got following error message:
```
Cannot import E:\DEV\ComfyUI_windows_portable\ComfyUI\custom_nodes\prompt-generator-comfyui module for custom nodes: Failed to import optimum.onnxruntime.modeling_ort because of the following error (look up to see its traceback):
Failed to import transformers.modeling_tf_utils because of the following error (look up to see its traceback):
No module named 'keras.engine'
```

**Operating System**
 -  Windows 11

** Python Version**
 - 3.10.6

** Transformers and optimum packages versions **
 Name: transformers
Version: 4.26.1 
Name: optimum
Version: 1.17.1

** ComfyUI Commit **
 -  ComfyUI Revision: 1969 [02409c30] | Released on '2024-02-12'

** prompt-generator-comfyui Commit **
 - latest

**Comment by alpertunga-bile** [comment]
Hello, thanks for reporting. It seems your ```transformers``` package is not up-to-date. The package version may be causing the problem. Please follow this [troubleshooting](https://github.com/alpertunga-bile/prompt-generator-comfyui#package-version) package update section and let me know if the issue is going on

**Comment by ultimatech-cn** [comment]
Thanks, problem solved.
